// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekcpwvsuniifexsdkjcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrY3B3dnN1bmlpZmV4c2RramNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDk3MTEsImV4cCI6MjA2NTIyNTcxMX0.kM53So9dYBUzb8B5gdJGUroS9t6IdKKs6L7p_JdSzCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);